
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import HappyVoteContractArtifactJson from './happy_vote_aztec-HappyVote.json' with { type: 'json' };
export const HappyVoteContractArtifact = loadContractArtifact(HappyVoteContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract HappyVote;
 */
export class HappyVoteContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, HappyVoteContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): HappyVoteContract {
    return Contract.at(address, HappyVoteContract.artifact, wallet) as HappyVoteContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<HappyVoteContract>(
      wallet,
      {
        artifact: HappyVoteContractArtifact,
        postDeployCtor: (instance, wallet) => HappyVoteContract.at(instance.address, wallet),
        args: [admin],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof HappyVoteContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<HappyVoteContract['methods'][M]>
  ) {
    return DeployMethod.create<HappyVoteContract>(
      opts.wallet,
      {
        artifact: HappyVoteContractArtifact,
        postDeployCtor: (instance, wallet) => HappyVoteContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return HappyVoteContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(HappyVoteContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'options_count' | 'privacy_policy' | 'eligibility_mode' | 'metadata_hash' | 'tally' | 'total_votes' | 'vote_ended' | 'active_at_block' | 'vote_claims' | 'open_ballots' | 'identity_claims' | 'sealed'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
options_count: {
      slot: new Fr(2n),
    },
privacy_policy: {
      slot: new Fr(3n),
    },
eligibility_mode: {
      slot: new Fr(4n),
    },
metadata_hash: {
      slot: new Fr(5n),
    },
tally: {
      slot: new Fr(6n),
    },
total_votes: {
      slot: new Fr(7n),
    },
vote_ended: {
      slot: new Fr(8n),
    },
active_at_block: {
      slot: new Fr(9n),
    },
vote_claims: {
      slot: new Fr(10n),
    },
open_ballots: {
      slot: new Fr(11n),
    },
identity_claims: {
      slot: new Fr(12n),
    },
sealed: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'admin' | 'options_count' | 'privacy_policy' | 'eligibility_mode' | 'metadata_hash' | 'tally' | 'total_votes' | 'vote_ended' | 'active_at_block' | 'vote_claims' | 'open_ballots' | 'identity_claims' | 'sealed'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cast_vote_open(poll_id: struct, option_id: field, identity_commitment: field) */
    cast_vote_open: ((poll_id: { id: FieldLike }, option_id: FieldLike, identity_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cast_vote_private(poll_id: struct, option_id: field, identity_commitment: field) */
    cast_vote_private: ((poll_id: { id: FieldLike }, option_id: FieldLike, identity_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_poll(poll_id: struct, options_count: integer, privacy_policy: integer, eligibility_mode: integer, metadata_hash: field, sealed: boolean) */
    create_poll: ((poll_id: { id: FieldLike }, options_count: (bigint | number), privacy_policy: (bigint | number), eligibility_mode: (bigint | number), metadata_hash: FieldLike, sealed: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** end_poll(poll_id: struct) */
    end_poll: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_eligibility_mode(poll_id: struct) */
    get_eligibility_mode: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_metadata_hash(poll_id: struct) */
    get_metadata_hash: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_open_ballot(poll_id: struct, voter: struct) */
    get_open_ballot: ((poll_id: { id: FieldLike }, voter: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_options_count(poll_id: struct) */
    get_options_count: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_privacy_policy(poll_id: struct) */
    get_privacy_policy: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_sealed(poll_id: struct) */
    get_sealed: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_tally(poll_id: struct, option_id: field) */
    get_tally: ((poll_id: { id: FieldLike }, option_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_votes(poll_id: struct) */
    get_total_votes: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_vote_ended(poll_id: struct) */
    get_vote_ended: ((poll_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_identity_voted(poll_id: struct, identity_commitment: field) */
    has_identity_voted: ((poll_id: { id: FieldLike }, identity_commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
